### ISSUE TITLE
navigate between editor group could be mapped to option/alt + tab

### ISSUE THREAD

**Issue by xc1427** [kasecato/vscode-intellij-idea-keybindings#101]
VSCode command `navigate between editor group` shows the same behavior as on Intellij with the keystroke  `option/alt + tab`. This command moves the cursor between all open groups

**Comment by kasecato** [comment]
@xc1427 thanks for your good suggestion! I released v0.2.18, please check it out and close this issue.

**Comment by xc1427** [comment]
FYI, this keybinding is name as "Goto Next Splitter" on Intellij. And it is only assigned on Macos but not windows.
