### ISSUE TITLE
shift+escape behaviors differently on VSCode and Intellij (macOS)

### ISSUE THREAD

**Issue by xc1427** [kasecato/vscode-intellij-idea-keybindings#103]
I examined source code of this repo related to `shift+escape` key-bindings. They are as below,

```
           {
                "key": "shift+escape",
                "mac": "shift+escape",
                "command": "workbench.action.toggleSidebarVisibility",
                "when": "!editorFocus && !terminalFocus && !problemFocus && !inDebugRepl",
                "intellij": "Hide active or last active window (Sidebar)"
            },
            {
                "key": "shift+escape",
                "mac": "shift+escape",
                "command": "workbench.actions.view.problems",
                "when": "problemFocus",
                "intellij": "Hide active or last active window (Problems)"
            },
            {
                "key": "shift+escape",
                "mac": "shift+escape",
                "command": "workbench.debug.action.toggleRepl",
                "when": "inDebugRepl",
                "intellij": "Hide active or last active window (Debug Console)"
            },
            {
                "key": "shift+escape",
                "mac": "shift+escape",
                "command": "workbench.action.terminal.toggleTerminal",
                "when": "terminalFocus",
                "intellij": "Hide active or last active window (Terminal)"
            },
```

IMHO, this configuration only partially respects behavior on Intellij, as on Intellij `esc+shift` will hide the last open window **even when editor has focus**. I see it is impossible to have a perfect match on VSCode because of its limited context clause. But I think the following code can be a nearly neat and simplified configuration.

```
   {
        "key": "shift+escape",
        "command": "workbench.action.toggleSidebarVisibility",
        "when": "sidebarVisible"
    },
    {
        "key": "shift+escape",
        "command": "workbench.action.terminal.toggleTerminal",
        "when": "terminalFocus"
    },
```

**Comment by xc1427** [comment]
FYI, the `sidebarVisible` seems to have bug. I filed an issue for VSCode https://github.com/Microsoft/vscode/issues/41645

**Comment by xc1427** [comment]
FYI, VSCode seems to have a `workbench.action.togglePanel` to toggle the bottom Panel (terminal, debug console, etc) , although it is not documented.

**Comment by spik3s** [comment]
What about if we just edit this:
```
{
    "key": "shift+escape",
    "mac": "shift+escape",
    "command": "workbench.action.toggleSidebarVisibility",
    "when": "!editorFocus && !terminalFocus && !problemFocus && !inDebugRepl",
    "intellij": "Hide active or last active window (Sidebar)"
}
```

and replace `"when"` with a line with removed `!editorFocus &&`
```
"when": "!terminalFocus && !problemFocus && !inDebugRepl"
```

My initial testing suggests that this solves the issue. What do you think?

**Comment by xc1427** [comment]
@spik3s Sorry, but this does not solve the issue. With your key bindings I still got sidebar open. But the expected behavior is to **always close** sidebar when `Shift+ESC` is hit. Could you please re-test it ?

This is my environment:
macOS version: 10.13.1
VSCode Version: 1.19.2
