### ISSUE TITLE
MacOS: Shift + Cmd + `(Maxmize Tool Window) can be mapped to Toggle Maximized Panel

### ISSUE THREAD

**Issue by xc1427** [kasecato/vscode-intellij-idea-keybindings#105]
On macOS, `Shift + Cmd +back-tick` toggles maximized tool window. This includes sidebar as well as bottom tool windows. This is not a perfect match to `Toggle Maximized Panel` on VSCode, since it only toggle the panel, i.e., the bottom one. But I think it doesn't matter.

**Comment by xc1427** [comment]
Is there any news ? @kasecato

**Comment by kasecato** [comment]
released this on v1.5.13
