### ISSUE TITLE
[Enhancement] CTRL + W scope management

### ISSUE THREAD

**Issue by i-oliva** [kasecato/vscode-intellij-idea-keybindings#109]
One of the most characteristic and most liked features of jetbrain users is the way in which the scope of CTWL + W works.

I'm not going to ask you to implement the same way, but something better. I have found a dependency that does it for you.

https://marketplace.visualstudio.com/items?itemName=letrieu.expand-region

I hope you implement it since in my personal opinion it would make a difference.

**Comment by kasecato** [comment]
@pavilion Thanks. VSCode has `editor.action.smartSelect.grow` and `editor.action.smartSelect.shrink`. I mapped these keys to `CTRL+W` and `CTRL+SHIFT+W` for Windows. I hope this feature will be smarter.
