### ISSUE TITLE
Git sync keybinding does not work

### ISSUE THREAD

**Issue by andrewda** [kasecato/vscode-intellij-idea-keybindings#115]
Command should be `git.sync` now:
https://github.com/Microsoft/vscode/blob/4e26c330a883853666e035cb366f3ecd3a0c1981/extensions/git/package.json#L283-L287

**Comment by kasecato** [comment]
@andrewda I just released it as [v0.2.24](https://marketplace.visualstudio.com/items?itemName=k--kato.intellij-idea-keybindings)! Please check it out.
