### ISSUE TITLE
git diff command 

### ISSUE THREAD

**Issue by quantuminformation** [kasecato/vscode-intellij-idea-keybindings#118]
Can we get a git diff command?

Normally in a mac I can do `cmd + d`

**Comment by QuantumInformation** [comment]
think I'm gonna just go with default keybindings

**Comment by kasecato** [comment]
Hi @QuantumInformation ,

Do you want to add `cmd+d` if VCS has focus?
![screen shot 2018-07-28 at 13 34 14](https://user-images.githubusercontent.com/10364603/43353116-fe804180-926a-11e8-889b-27be5793a74c.png)

Thanks

**Comment by kasecato** [comment]
vscode is supporting show diff in the SCM views

**Comment by kasecato** [comment]
```js
            {
                "key": "ctrl+d",
                "mac": "cmd+d",
                "command": "git.openChange",
                "when": "focusedView == 'workbench.view.scm'",
                "intellij": "Show diff"
            },
```
