### ISSUE TITLE
[ctrl+d] Duplicate current line or selected block in vscode is not equal with JetBrans Webstrom

### ISSUE THREAD

**Issue by DarkFlame** [kasecato/vscode-intellij-idea-keybindings#123]
when i select table and press [ ctrl + d ] 

![image](https://user-images.githubusercontent.com/9960131/44864748-081c5c80-acb3-11e8-939f-0ce8b3304883.png)

is my expect 

`
    <table></table></table>
`

but result is 
`    <table></table>
    <table></table>
`

**Comment by kasecato** [comment]
works same as expected for now
