### ISSUE TITLE
The plugin doesn't work 

### ISSUE THREAD

**Issue by mahmoud-bahaa** [kasecato/vscode-intellij-idea-keybindings#125]
I have vscode version 1.26.1 on Windows 10, I tried installing and reloading but it doesn't work.  I also tried running vscode as an administrator but still no luck the keycode mappings aren't even updated.

Please help.

**Comment by uguraktas** [comment]
I have the same problem

**Comment by kasecato** [comment]
@mahmoud-bahaa @uguraktas 
This extension requires a vscode of 1.27.0 or higher.
