### ISSUE TITLE
Breadcrumbs hotkey

### ISSUE THREAD

**Issue by rinormaloku** [kasecato/vscode-intellij-idea-keybindings#127]
IntelliJ has the Hotkey for Breadcums (a.k.a Jump to Navigation Bar with key Alt + Home)

Jump to Navigation Bar is equivalent to the new feature [Breadcrumbs](https://code.visualstudio.com/updates/v1_27#_breadcrumbs-improvements)

**Comment by kasecato** [comment]
@rinormaloku Sorry for my late reply. I just released [v0.2.27](https://marketplace.visualstudio.com/items?itemName=k--kato.intellij-idea-keybindings). Please check it.

**Comment by rinormaloku** [comment]
Hey @kasecato, yeah works perfectly :) :) 
👍 👍
