### ISSUE TITLE
cmd+n is not working

### ISSUE THREAD

**Issue by gagoman** [kasecato/vscode-intellij-idea-keybindings#133]
[This](https://github.com/kasecato/vscode-intellij-idea-keybindings/commit/3f1b9fb460d98aa6436150a7a341c2be5af6b9b5) change has broken default cmd+n behavior because `-workbench.action.files.newUntitledFile` is unknown command. I have checked on a fresh copy also. Is it broken only for me?

**Comment by lautumn1990** [comment]
Me too. It's so sad.

**Comment by tmhpfnr** [comment]
#MeToo

**Comment by flashsphere** [comment]
#134 should fix it.

**Comment by huiqiangyang** [comment]
Me too

**Comment by Jimtrim** [comment]
I can confirm that the issue @flashsphere linked to had a solution, but I would still want the maintainers of this plugin to fix this binding in the actual plugin.

**Comment by kasecato** [comment]
@gagoman @Jimtrim @lautumn1990 @huiqiangyang Thanks! I just release v0.2.29. Please check it 🎉

**Comment by gagoman** [comment]
Latest version works. Thank you a lot.
