### ISSUE TITLE
navigateToLastEditLocation not released

### ISSUE THREAD

**Issue by covertbert** [kasecato/vscode-intellij-idea-keybindings#135]
Hey so I know I did some of the work for this shortcut (#131) and you definitely merged it after committing yourself but it doesn't seem to be in the release or the master branch. Any ideas what's up here?

**Comment by kasecato** [comment]
@covertbert Sorry, it was my release mistake. Please check v0.2.29. 🎉

**Comment by covertbert** [comment]
Thanks @kasecato but now it's being overridden by the original keymapping of `cmd+shift+backspace`. Is this because you have to remove the original keymapping for this to work? I was under the impression that when changing a keymapping in an extension it would autmoatically override the default? Maybe this is just a problem with my setup, is it happening for you too?

<img width="933" alt="screen shot 2018-11-19 at 10 07 21" src="https://user-images.githubusercontent.com/8471383/48700119-1fe4ec00-ebe3-11e8-99b8-8ac85fb8e6a2.png">

**Comment by covertbert** [comment]
Ignore my stupidity, I just realised that the `previous edit point` override was in my user keybindings. Monday mornings  🙈

Thanks for getting that sorted!
