### ISSUE TITLE
ALT + INTER can't work

### ISSUE THREAD

**Issue by CatchTheDog** [kasecato/vscode-intellij-idea-keybindings#139]
I have vscode version 1.30 on Windows 10, I tried installing and reloading but the keymap to override function(alt + inter ) in IDEA  does not work. 

Please help.

**Comment by kasecato** [comment]
Please use `alt+enter` that is quick fix.
![alt+enter](https://user-images.githubusercontent.com/10364603/59545562-0cbcb380-8f5b-11e9-8de2-9fc5ae4087c2.gif)

**Comment by kasecato** [comment]
duplicated with #140
