### ISSUE TITLE
ALT + INSERT  key map does not work

### ISSUE THREAD

**Issue by CatchTheDog** [kasecato/vscode-intellij-idea-keybindings#140]
Issue Type: <b>Bug</b>

I have vscode on win10 and I install IntelijKeyBingdings plugin, and the key map for overriding functions can't work .

Extension version: 0.2.30
VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by CauchyAbel** [comment]
I am using 1.33.1 version VS code and Windows 10 and it doesn't work either.

**Comment by kasecato** [comment]
When we don't have a code actions provider (a.k.a. editorHasCodeActionsProvider), `alt+insert` won't work. I checked it and it works with Language Support plugin
