### ISSUE TITLE
Extract Method/Variable/Constant does not work

### ISSUE THREAD

**Issue by omryoz** [kasecato/vscode-intellij-idea-keybindings#142]
When trying to extract variable / method - I get the following error
![image](https://user-images.githubusercontent.com/653663/52038161-04c71e80-253a-11e9-840a-0eee704dcc11.png)

**Comment by kasecato** [comment]
This means there is no refactoring suggestion here
https://code.visualstudio.com/docs/editor/refactoring#_extensions-with-refactorings
