### ISSUE TITLE
New Binding Request: (VS Code)`Revert Selected Range` can be mapped to `Revert...`(Intellij)

### ISSUE THREAD

**Issue by xc1427** [kasecato/vscode-intellij-idea-keybindings#145]
As title of this issue suggested, `Revert Selected Range` in VS Code could be mapped to `Revert...`in Intellij which has a default keybinding ⌥⌘Z, in spite of a few subtle differences.

**Comment by kasecato** [comment]
@xc1427 Thanks always! I released `v0.2.33`. Please check it.
