### ISSUE TITLE
New Binding Request: `Structure`(⌘7) can be ported by making use of `Focus on outline view`

### ISSUE THREAD

**Issue by xc1427** [kasecato/vscode-intellij-idea-keybindings#146]
As the title of this issue says, we might make use of `Focus on Outline View` in VS Code in order to port `Structure` Command in Intellij.

**Comment by kasecato** [comment]
@xc1427 That sounds good! I released `v0.2.33`. Please check it. Thanks 👍

**Comment by yunti** [comment]
Works well to open it.  Is there a way we can hide it again like intellij as cmd+7 as show/hide structure tool?
