### ISSUE TITLE
ctrl + home mapping for macOS

### ISSUE THREAD

**Issue by WangLeto** [kasecato/vscode-intellij-idea-keybindings#149]
I use `ctrl + home` to jump to the first character on Windows or Linux editor, but what is the mapping for mac? I tried `fn + ctrl + left` and etc, nothing work; or is there is a configurable entry in vs code key binding for this?

**Comment by kasecato** [comment]
Hi @WangLeto ,
I've just released it. Please check it!
Thanks!
