### ISSUE TITLE
Native shortcut sequences beginning with ctrl+k clash with IntelliJ ctrl+k commit command

### ISSUE THREAD

**Issue by emilborowiec** [kasecato/vscode-intellij-idea-keybindings#150]
It looks like ctrl+k in VS Code has the semantics of 'begin command input'. On IntelliJ keymap, all those commands are blocked because of commit command kicking in after ctrl+k press. 

The solution could be to change all the VS Code native **ctrl+k <another stroke>** commands to begin with something else. ctrl+alt+k looks to be a free option.

**Comment by kasecato** [comment]
@emilborowiec @matejtro I released `v0.2.33` including this fix that `ctrl+alt+k`. Thanks 👍
