### ISSUE TITLE
Should Ctrl+B be able to display a list of callers for functions?

### ISSUE THREAD

**Issue by rxliuli** [kasecato/vscode-intellij-idea-keybindings#151]
As in the title, in IDEA, all callers can be listed on the function by **Ctrl+B**. If there is only one, they will jump directly, but they are bound by default in **VSCode-IDEA-Keybindings** I hope that I can modify it! (=^･ω･^)y＝

**Comment by rxliuli** [comment]
Added: ** Ctrl+B** should be able to automatically decide how to operate according to the context.
E.g:

1. I am in a function call

```js
Function fn() {}

Fn()
```

When the cursor is on `fn()`, it is obvious that my generation wants to jump to the definition of the function. When the cursor is on `function fn() {}`, what I want more is to display all caller lists!

Thanks a lot for the shortcut mapping of `IDEA => VSCode`, I am a user of IDEA.

**Comment by rxliuli** [comment]
Is there any progress in this issue?

**Comment by kasecato** [comment]
Seems like this request was resolved by goToDeclaration of VS Code. goToDeclaration will handle like IntelliJ

- editor.action.goToDeclaration
