### ISSUE TITLE
Missing command - Expand recursively

### ISSUE THREAD

**Issue by yunti** [kasecato/vscode-intellij-idea-keybindings#152]
Code folding for the block and expand all/collapse all work well.  However in the readme, it doesn't mention `Expand Recursively`. which is Alt+cmd + = by default.

This would be a great addition to the keybindings

https://www.jetbrains.com/help/pycharm/code-folding-commands.html

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/1826271/59940319-4e18fb80-9452-11e9-9b05-e4d544478b06.png">

**Comment by yunti** [comment]
Seems like vscode does support this:

Ctrl+Shift+[    Fold (collapse) region  editor.fold
Ctrl+Shift+]    Unfold (uncollapse) region  editor.unfold
Ctrl+K Ctrl+[   Fold (collapse) all subregions  editor.foldRecursively
Ctrl+K Ctrl+]   Unfold (uncollapse) all subregions  editor.unfoldRecursively
Ctrl+K Ctrl+0   Fold (collapse) all regions editor.foldAll
Ctrl+K Ctrl+J   Unfold (uncollapse) all regions

https://stackoverflow.com/questions/39718412/visual-studio-code-keyboard-shortcuts-expand-collapse-all#39718649

**Comment by yunti** [comment]
Just tested adding this manually it works well - just like intellij

**Comment by kasecato** [comment]
Thanks @yunti . I added it. Please check it.

**Comment by yunti** [comment]
works perfectly thanks

**Comment by KrisLau** [comment]
Still missing for me
