### ISSUE TITLE
ctrl+f has no "when" so always searches in editor, so finding in terminal / webview is clobbered

### ISSUE THREAD

**Issue by vitaminj** [kasecato/vscode-intellij-idea-keybindings#153]
With this extension enabled, cannot search in the terminal and other panes, keymap editor, or indeed in extension marketplace pages.
Can you omit the find entry from your keymap entirely, as it's the same as the default?

**Comment by kasecato** [comment]
Thanks @vitaminj , I fixed it. Please check it.

**Comment by vitaminj** [comment]
Yep, works great now, thanks for the quick response!
