### ISSUE TITLE
[navigation] cursorTop + cursorBottom

### ISSUE THREAD

**Issue by constb** [kasecato/vscode-intellij-idea-keybindings#154]
JetBrains IDEs have ⌘+Home and ⌘+End to go to the top and to the bottom of the open editor. Both don't work with this plugin.

VS Code defaults are ⌘+Up and ⌘+Down. The former actually works because it's not overridden, the latter on the other hand is now 'go to definition'.

Please add JetBrains-compatible navigation shortcuts to the plugin. According to the keybindings page their Command Ids are `cursorTop` and `cursorBottom`.

**Comment by kasecato** [comment]
Related with #149

**Comment by kasecato** [comment]
Hi @constb ,
I've just released it. Please check it!
Thanks!
