### ISSUE TITLE
Zoom In and Zoom Out shortcuts don't work `cmd +` and `cmd -`

### ISSUE THREAD

**Issue by pete-woods** [kasecato/vscode-intellij-idea-keybindings#155]
Not sure what's wrong, but the keyboard shortcuts for these don't work after installing.

(On Mac)

**Comment by BinaryShrub** [comment]
Is this being worked on @kasecato ?

**Comment by kasecato** [comment]
@pete-woods @BinaryShrub I think `cmd + -` is a `Collapse code block` and `cmd + +` is a `Expand code block`. What change would you like?

**Comment by pete-woods** [comment]
I guess we were expecting VS code shortcuts for zooming to work. In the menus they still show the hint as “Zoom In `cmd-+`”.

Is zoom mapped to some other shortcut by your plugin?

**Comment by pete-woods** [comment]
Looks like IntelliJ calls it “increase font size”

**Comment by kasecato** [comment]
There is no binding. cmd + mousewheel looks good, but by default it was off.

<img width="884" alt="general" src="https://user-images.githubusercontent.com/10364603/68544511-42c96b00-0407-11ea-9256-299afcf64862.png">
<img width="1193" alt="keybindings_font" src="https://user-images.githubusercontent.com/10364603/68544512-42c96b00-0407-11ea-962a-fe393e9ff7c9.png">
