### ISSUE TITLE
how do I quick open a file when ctrl+p is overrode?

### ISSUE THREAD

**Issue by ted-dev-42** [kasecato/vscode-intellij-idea-keybindings#156]
As far as I know, shift + shift is not implemented.

**Comment by shibumi** [comment]
@xcjiang You can use: `ctrl+shift+p` and then just press `backspace` and you will find yourself in the fuzzy file search dialog. It's not nice, but it's at least a workaround.

**Comment by iwanderer** [comment]
Just in case, now we  can use `Ctrl + Shift + n` to quick open a file.

**Comment by kasecato** [comment]
We can use `shift shift` 
https://github.com/kasecato/vscode-intellij-idea-keybindings/pull/210
