### ISSUE TITLE
Change Cmd+D from "editor.action.copyLinesDownAction" to new "editor.action.duplicateSelection"

### ISSUE THREAD

**Issue by fabb** [kasecato/vscode-intellij-idea-keybindings#157]
A new "editor.action.duplicateSelection" was added to VSCode that mimics the IntelliJ behavior 🎉

https://github.com/microsoft/vscode/issues/2075

It would be nice if the Cmd+D action would be changed to this new action.

**Comment by kasecato** [comment]
Hi @fabb ,
I've just released it. Please check it!
It seems that the release is still insider build only.
Thanks!

**Comment by Hoffs** [comment]
So this actually breaks the extension as the `editor.action.duplicateSelection` is insider only. So if the client is not running insider build the command is just failing with:
```
command 'editor.action.duplicateSelection' not found
```

**Comment by alexandrtovmach** [comment]
Related issue #161

**Comment by kasecato** [comment]
@fabb @AlexAkhremenko @Hoffs I just released it. Please Check it.

**Comment by Hoffs** [comment]
works fine :)

**Comment by kasecato** [comment]
The day has finally come to close.
