### ISSUE TITLE
Ctrl+D doesn't work for duplicate selection

### ISSUE THREAD

**Issue by alexandrtovmach** [kasecato/vscode-intellij-idea-keybindings#161]
## Environment
- IntelliJ IDEA Keybindings v0.2.35
- VSCode v1.39.2
- Windows 10

## Steps to reproduce
1. Select multiline code
2. `Ctrl+D`

## Expected result
Multiline code duplicating below selected code

## Actual result
Error message 
> command 'editor.action.duplicateSelection' not found

![image](https://user-images.githubusercontent.com/28801003/67266162-2bf2c100-f4b8-11e9-88a4-462cd8a17a8f.png)

I think it somehow related to https://github.com/kasecato/vscode-intellij-idea-keybindings/commit/1ac777be9c34168379f70145543eeecb1ae9fd24

**Comment by kasecato** [comment]
Hi @alexandrtovmach ,
Thanks for your detailed report. The keybindings will release in [October milestone](https://github.com/microsoft/vscode/milestone/102). If it's not released even after Oct 31, I will revert it.
Thanks

**Comment by Hoffs** [comment]
Wouldn't it make more sense to release it after Oct31 (or after october release in general) as it is more likely that most users of the extension aren't running insider builds and with the current approach the command will be broken for 8+ days for majority (my guess) of users.

**Comment by kasecato** [comment]
@Hoffs @alexandrtovmach I reverted it.

**Comment by alexandrtovmach** [comment]
@kasecato Thank you
