### ISSUE TITLE
Paste Command not found

### ISSUE THREAD

**Issue by NickBolles** [kasecato/vscode-intellij-idea-keybindings#163]
I'm getting a toast notification that reads:
```
command 'editor.action.clipboardPasteAction' not found
```

I'm using [code-server](https://github.com/cdr/code-server), v2: 
```
Version: 1.39.2
Commit: f133b00851c6c05aedaf78ff139443a46cd8d036
Date: 2019-10-21T22:06:51.355Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
```

**Comment by NickBolles** [comment]
I'm not able to reproduce this with a local windows install on 1.39.2. Maybe this is a code-server compatibility issue? 

local vscode info:
```
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763
```

**Comment by NickBolles** [comment]
see https://github.com/cdr/code-server/issues/1105 for my temporary solution, to remove the offending keybinding and use the stock paste.

**Comment by kasecato** [comment]
@NickBolles  Should I remove the keybinding and let the VSCode default settings?

**Comment by NickBolles** [comment]
@kasecato I'm not entirely sure. But that seems like it would work given my workaround just removed the setting defined by this extension.

**Comment by kasecato** [comment]
@NickBolles I removed this settings from package.json. Please check it.
