### ISSUE TITLE
How do I apply the keybindings?

### ISSUE THREAD

**Issue by raekw0n** [kasecato/vscode-intellij-idea-keybindings#167]
I've installed this extension via the Marketplace and reloaded my vscode, however my keybindings haven't changed.

How do I enable the new keybindings?

**Comment by raekw0n** [comment]
I should probably mention what I'm running on:

Linux Mint 19.2 Tina
VS Code 1.40.1

**Comment by kasecato** [comment]
I'll try it on Linux Mint.

**Comment by MarkZhuVUW** [comment]
I have the same problem. 
I am running it on Windows 10

**Comment by Superblazer** [comment]
Me too, the keybindings do not work in windows 10. 
I'm using the latest version of VS Code.

**Comment by johanhaleby** [comment]
Doesn't work for me either. 

Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T17:58:38.338Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

**Comment by CellycoMobiles** [comment]
4me2

Java code settings.json 👍 
`
{
    "workbench.colorTheme": "Visual Studio Dark",
    "workbench.iconTheme": null,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "java.configuration.checkProjectSettingsExclusions": false,
    "files.autoSave": "afterDelay",
    "sqltools.connections": [],
    "explorer.confirmDelete": false,
    "java.jdt.ls.vmargs": "-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -javaagent:\"/Users/sergey/.vscode/extensions/gabrielbb.vscode-lombok-0.9.9/server/lombok.jar\"",
    "keyboard.touchbar.enabled": false,
    "window.zoomLevel": 0,
    "[java]": {
        
    }
}
`
VSCode :

`Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0`

**Comment by tedyoung** [comment]
Is there a way to "manually" install this since doing it via the extension mechanism doesn't seem to be working for me either.

**Comment by bcetienne** [comment]
Same problem, I've downloaded the keybinding, reloaded vs code and nothing change

Extension version: 0.2.37
VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz (4 x 3406)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (2.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by JuanxCursed** [comment]
Same problem,

**Comment by tedyoung** [comment]
Does anyone have a workaround or solution for this? Installing manually or differently?

**Comment by JuanxCursed** [comment]
I managed to make work partially (less than half of shortcuts), unfortunately not was good enough for me. 
 These are the step I did:

- Reset all settings to default on vscode (including extensions)
- Re-install intellij idea keybindings
- Re-install others extensions you may have
- Test

I hope this help you.

**Comment by raekw0n** [comment]
Just to update, this issue appears to have been fixed as of 0.2.41. Running VSCode 1.47.2 on Linux Mint 19.3 (Tricia), I have installed the extension, reloaded my window and can confirm that the keybindings have successfully updated.
