### ISSUE TITLE
how can text size zoom?

### ISSUE THREAD

**Issue by pain3992** [kasecato/vscode-intellij-idea-keybindings#168]
before shortcut is cmd + '+' or cmd + '-'

however, i added vscode-intellij-idea-keybindings

where is textsize ++ . & textsize -- ??

**Comment by kasecato** [comment]
@pain3992 @pete-woods  How about Command+Mouse wheel?
https://github.com/kasecato/vscode-intellij-idea-keybindings/issues/155#issuecomment-552193787

**Comment by pete-woods** [comment]
Seems reasonable if that’s the default IntelliJ shortcut

**Comment by kasecato** [comment]
- Increase Font Size in All Editors = editor.action.fontZoomIn
  - Win/Linux: alt+shift+.
  - macOS: ctrl+shift+.
- Decrease Font Size in All Editors = editor.action.fontZoomOut
  - Win/Linux: alt+shift+,
  - macOS: ctrl+shift+,
