### ISSUE TITLE
shortcut for search everywhere is not working

### ISSUE THREAD

**Issue by melihs** [kasecato/vscode-intellij-idea-keybindings#170]
`shift + shift `shortcut does not work in this plugin. I have to use the standard shortcut to search everywhere `( cmd + shift + p )`. I think there is a **bug**.

- OS : Mac OS
- Visual Studio Code version: 1.41
- extension version:   0.2.37

**Comment by imliam** [comment]
This isn't a bug with this package, but VSCode simply doesn't let you bind modifier keys in that way - it's out of control of this package.

**Comment by melihs** [comment]
Is there alternative solution ?

**Comment by d70rr3s** [comment]
Perhaps can be used in tandem with [kbysiec.vscode-search-everywhere
](https://github.com/kbysiec/vscode-search-everywhere) extension.

**Comment by d70rr3s** [comment]
It's a VSCode issue https://github.com/Microsoft/vscode/issues/5280 AFAIK `Cmd + Shift + P` search for commands, not files or symbols. 

I'm using [kbysiec.vscode-search-everywhere
](https://github.com/kbysiec/vscode-search-everywhere) which offers the "Search everywhere" feature and you can bind your preferred shortcut to it (except for SS of course).

**Comment by PathToLife** [comment]
I added a PR for "Shift Shift". Hopefully we can add it here if everything goes ahead.
https://github.com/microsoft/vscode/pull/115190

**Comment by kasecato** [comment]
Released v1.4.0
