### ISSUE TITLE
run previous Go test

### ISSUE THREAD

**Issue by glyn** [kasecato/vscode-intellij-idea-keybindings#171]
On IntelliJ on macOS, this very useful function is bound to ctrl+r.

In vscode (with the intellij keybinding) ctrl+r is bound to "File: Open Recent".

Would it be feasible to rebind ctrl+r to `Go: Test Previous` as part of the intellij keybinding?

**Comment by kasecato** [comment]
@glyn Thanks. With VSCode default settings, ctrl+r on macOS is showing recently used files. I should to fix this.

Checking the default bindings for IntelliJ, it seems that macOS has "Run" assigned to it. So, I should remap it to "Tasks: Run Task". Is that okay?

- macOS: ctrl+r = Run/Debug
![macos](https://user-images.githubusercontent.com/10364603/77499254-f6059e80-6e94-11ea-9942-c30a5dd38dca.png)

- Windows /Linux: ctrl+r = Replace
![win_linux](https://user-images.githubusercontent.com/10364603/77499269-00c03380-6e95-11ea-8aef-1db7e0444438.png)

- default keymap - JetBrains, https://resources.jetbrains.com/storage/products/intellij-idea/docs/IntelliJIDEA_ReferenceCard.pdf

**Comment by glyn** [comment]
> Checking the default bindings for IntelliJ, it seems that macOS has "Run" assigned to it. So, I should remap it to "Tasks: Run Task". Is that okay?

Thanks, that may suit some languages, but it doesn't help for Go development. "Tasks: Run Task" doesn't re-run the last Go test, it produces a message "No task to run found. Configure Tasks...".

(My current workaround is to manually bind ctrl+r to 'Go: Test Previous'.)

**Comment by kasecato** [comment]
@glyn Okay, I will change it to 'Go: Test Previous' when "editorLangId == go" 👌
https://code.visualstudio.com/docs/getstarted/keybindings#_contexts

**Comment by kasecato** [comment]
@glyn I've released it in [v.0.2.38](https://marketplace.visualstudio.com/items?itemName=k--kato.intellij-idea-keybindings). Please check it.

**Comment by glyn** [comment]
Excellent, that's a great solution. Thanks!
