### ISSUE TITLE
Shortcuts not listed in the context menus

### ISSUE THREAD

**Issue by danlester** [kasecato/vscode-intellij-idea-keybindings#172]
Thank you for these keybindings. The main reason for trying this out was because IntelliJ shortcuts seem to rely less on F keys which (more or less) no longer exist on the Mac.

The extension works as expected when I press the IntelliJ shortcuts, except that the context menus etc in VSCode still show the old mappings. (And in fact, the old mappings also seem to work)

For example, CMD+B to jump to definition works fine. But so does F12, and on the context menu it lists F12 as the shortcut to use. This isn't helpful for learning the shortcuts...

Is there any way to get VSCode to fully adopt the new keybindings, without ending up in this mixed state?

Many thanks for your thoughts, although of course this may be due to VSCode limitations.

**Comment by kasecato** [comment]
@danlester Thanks. I can remove a specific key binding rule of VSCode. In the meantime, all I can do is disable F12, but I'll add other disabling if you request it 🔨
https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule

**Comment by danlester** [comment]
Thank you for the reply. To be honest, removing the F12 wouldn't really make much difference to the usability problem as I see it - the context menu needs to actually display CMD+B instead of F12 to help with navigating/learning the shortcuts. It doesn't sound like you think that's possible, at which point having both shortcuts working isn't a problem in itself.

**Comment by kasecato** [comment]
@danlester Thanks
