### ISSUE TITLE
Binding "Change All Occurences" to Shift+F6

### ISSUE THREAD

**Issue by goncalossilva** [kasecato/vscode-intellij-idea-keybindings#180]
In some contexts, this is the only rename function. Its key is `editor.action.changeAll`, and its condition differs from renaming as it doesn't include `editorHasRenameProvider`.

**Comment by kasecato** [comment]
Hi @goncalossilva , thanks for your great idea! I just released [v0.2.40](https://marketplace.visualstudio.com/items?itemName=k--kato.intellij-idea-keybindings), please check it 👍

**Comment by goncalossilva** [comment]
Awesome! It works great. :ok_hand:
