### ISSUE TITLE
keybinding for comment/uncomment with block comment is incorrect

### ISSUE THREAD

**Issue by unclebob418** [kasecato/vscode-intellij-idea-keybindings#183]
according to reference 2. IntelliJ IDEA DEFAULT KEYMAP, https://resources.jetbrains.com/storage/products/intellij-idea/docs/IntelliJIDEA_ReferenceCard.pdf
the keyboard shortcut should be
`Comment / uncomment with block comment Ctrl + Shift + /`
but the shortcut for this plugin is
`ctrl+alt+/	cmd+alt+/	Comment/uncomment with block comment`

**Comment by kasecato** [comment]
@unclebob418  thank you for reporting to me about this bug. I just fixed on [v0.2.41](https://marketplace.visualstudio.com/items?itemName=k--kato.intellij-idea-keybindings). Please check it 👍

**Comment by unclebob418** [comment]
This works fine now, thanks a lot for this!
