### ISSUE TITLE
"crtl+b" doesn't work in angular project properly

### ISSUE THREAD

**Issue by yshukh** [kasecato/vscode-intellij-idea-keybindings#186]
![image](https://user-images.githubusercontent.com/20341714/92718242-3a64f800-f36a-11ea-9960-1a356136b277.png)
When I clicked "ctrl+b" on selector value I expected to go to usage of this selector or show list of usages to pick needed one. The same with "templateUrl" and "styleUrls" values
Thanks

**Comment by fatiz1997** [comment]
Actually,  "templateUrl" and "styleUrls" work fine, after click the editor falls down to proper file, so just selector improvement left

**Comment by kasecato** [comment]
Looks like `ctrl+b` is working fine, but Language Server Protocol is not. Please ask https://github.com/angular/vscode-ng-language-service
