### ISSUE TITLE
CTRL + S conflicts with Eslint

### ISSUE THREAD

**Issue by jahnli** [kasecato/vscode-intellij-idea-keybindings#187]
Eslint auto-repair is currently used in the project, but after vscode-Intellij-Ideal-KeyBindings is installed, CTRL + S will fail, resulting in failure to trigger esLINT auto-repair

**Comment by rvndsngwn** [comment]
cmd+s not working on MacBook Air M1
(VS Code Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:25.642Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin arm64 20.4.0 )

**Comment by kasecato** [comment]
eslint auto fix is part of VS Code's Code Action on Save infrastructure and computes all possible fixes in one round, so there should be no conflict in terms of mechanics
https://github.com/microsoft/vscode-eslint?tab=readme-ov-file#version-204

**Comment by kasecato** [comment]
`cms+s` is working fine in my M1 Mac. Please check your keybindings is not conflict with `cmd+s`
