### ISSUE TITLE
Keymap for completion

### ISSUE THREAD

**Issue by ice1000** [kasecato/vscode-intellij-idea-keybindings#189]
Now VSCode has Shift+Tab to do "replace completion" like in intellij's "Tab". I wish this plugin can map tab to the shift+tab behaviour.

VSCode version 1.51

**Comment by kasecato** [comment]
@ice1000 Thank you for your great request. I just released it `v1.3.0`. Please check it.

**Comment by ice1000** [comment]
Thank you very much!
