### ISSUE TITLE
Tool Windows keymaps conflic when writing ALT Codes

### ISSUE THREAD

**Issue by Davoleo** [kasecato/vscode-intellij-idea-keybindings#190]
When I try writing a char that doesn't exist on my keyboard (for example \`) by using the key combination: `Alt + 96` on the numpad I get a warning message about one of these keymaps: https://github.com/kasecato/vscode-intellij-idea-keybindings#general

Solutions to this may be:
- remove the numpad aliases of the keymaps referenced above (I don't think most people use those aliases anyways)
- make them effective only when the user is not actively writing in the editor / when the editor is not selected

**Comment by kasecato** [comment]
This extension may trigger `alt + numpad9` (Open/Close Git) by `alt + numpad9 numpad6`
Open Git works even in the editor in IntelliJ.
numpad is difficult to change here because it was previously requested and supported by numpad users
