### ISSUE TITLE
Refactoring shortcuts not work on MacOS

### ISSUE THREAD

**Issue by suerta-git** [kasecato/vscode-intellij-idea-keybindings#192]
When I use the shortcut like `cmd+alt+m` `cmd+alt+v`, vscode displays a notification like this:
<img width="502" alt="Screen Shot 2021-01-06 at 10 18 02 AM" src="https://user-images.githubusercontent.com/59438603/103721817-9a626700-5009-11eb-8f0a-475050d0efc5.png">

But if I click this
<img width="201" alt="Screen Shot 2021-01-06 at 10 27 53 AM" src="https://user-images.githubusercontent.com/59438603/103721934-d8f82180-5009-11eb-9e31-5f94cda200fc.png">
It works well.

**Comment by BugsBuenny** [comment]
I have exactly the same issue on Windows when editing Python files:
![image](https://user-images.githubusercontent.com/120019484/210100519-99b78a26-f0a5-4cbc-9044-1c396977a0b1.png)

But refactoring using the lightbulb is working fine:
![image](https://user-images.githubusercontent.com/120019484/210100629-1dfefb10-59d4-4bd6-a788-e1b2db019e89.png)
