### ISSUE TITLE
Fresh install could not find an import command.

### ISSUE THREAD

**Issue by Tumurtogtokh** [kasecato/vscode-intellij-idea-keybindings#201]
Hi,

I installed the extension and tried to run "Import IntelliJ Keybindings (XML)" command but got this error:

`Command 'IntelliJ Keybindings: Import IntelliJ Keybindngs (XML)' resulted in an error (command 'IntelliJ/importFile' not found)`

I have tried v1.10 and v1.2.0 and use Centos8.

Thanks.

**Comment by kasecato** [comment]
Hi @Tumurtogtokh 
I've also reproduced it on Ubuntu. I just released it v1.2.1.
It was happening on a combination of Linux and VS Code Marketplace.
Perhaps I should report it to VS Code. We can use "/" as a command, but when we publish from VS Code Marketplace, we get a command not found error on Linux.

**Comment by kasecato** [comment]
#203

**Comment by kasecato** [comment]
I just released `v1.2.2` Please try it.

https://github.com/kasecato/vscode-intellij-idea-keybindings/pull/204

**Comment by Tumurtogtokh** [comment]
Thanks @kasecato ! I confirm that it is working with both v1.2.2 and v1.3.0. Cheers for the quick fix :)
