### ISSUE TITLE
Unable to import keybindings

### ISSUE THREAD

**Issue by djnoddyp** [kasecato/vscode-intellij-idea-keybindings#203]
Pressing Ctrl+Shift+P and selecting "IntelliJ Keybindings: Import Intellik Keybindings (XML)" results in error:

``Command 'IntelliJ Keybindings: Import IntelliJ Keybindngs (XML)' resulted in an error (command 'intellij.importKeyMapsSchema' not found)``

Extension version: v1.2.1
VS code info:

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.0-40-generic

**Comment by kasecato** [comment]
![Screen Shot 2021-01-30 at 5 04 09 AM](https://user-images.githubusercontent.com/10364603/106322095-a532b380-62b8-11eb-849d-ace513096dd9.png)

**Comment by kasecato** [comment]
@djnoddyp  Thank you for your detailed report.
I've also reproduced it on `v1.2.1`. I fixed it and released it `v1.2.2`.
Please try it.
![Screen Shot 2021-01-30 at 6 35 53 AM](https://user-images.githubusercontent.com/10364603/106329840-81299f00-62c5-11eb-947f-da84f5f29e91.png)

**Comment by djnoddyp** [comment]
Yes I tried and it's working now- thank you very much for fixing it so quickly. BTW your extension is the sole reason I use VS Code :+1:

**Comment by consal** [comment]
I have the same issue in 1.56, could you check?
