### ISSUE TITLE
Export tutorial outdated

### ISSUE THREAD

**Issue by jakobbraun** [kasecato/vscode-intellij-idea-keybindings#208]
The tutorial on how to export the keybindings from IDEA in the README seems to be outdated: It does no longer contain `Key maps (schemas)`.
![grafik](https://user-images.githubusercontent.com/18247545/107405987-32bba200-6b08-11eb-8f57-8dccc4715e80.png)
*(InteliJ IDEA 202.3.2 Community Edition on Ubuntu Linux)*

Of yourse you can't change the export in IDEA, but in case there is an other way for exporting the settings it would be great if you could show it. Otherwise I would suggest to remove the export tutorial since it is confusing.

**Comment by anooprh** [comment]
This would be awesome if it's fixed. I'm trying to import the old IntelliJ KeyMaps (prior to Mac OS 10.5) and it seems that there is now way right now to import different keymaps from intelliJ

**Comment by kasecato** [comment]
We should make a plugin in IntelliJ that outputs all keymaps, not just the differences.

> A custom keymap is not a full copy of its parent keymap. It inherits unmodified shortcuts from the parent keymap and defines only those that were changed.

- https://www.jetbrains.com/help/idea/configuring-keyboard-and-mouse-shortcuts.html
- https://github.com/kasecato/vscode-intellij-idea-keybindings#known-issues-intellij-importer

**Comment by tyasird** [comment]
I couldn't export keymaps for pycharm.

**Comment by kasecato** [comment]
removed guide
