### ISSUE TITLE
Ctrl + Enter started to conflict with git commit after v1.4.0

### ISSUE THREAD

**Issue by hs-davydov** [kasecato/vscode-intellij-idea-keybindings#212]
![Untitled](https://user-images.githubusercontent.com/74358320/110695554-b72a3f00-81f2-11eb-9446-35534f38e7bc.png)
Git commit or `scm.acceptInput` by default has `ctrl+enter` keybinding. It stopped working few days ago, presumably after this commit https://github.com/kasecato/vscode-intellij-idea-keybindings/commit/da207fb922e73662f6a2bbe0b7537938fc54aaaa

**Comment by hs-davydov** [comment]
as a workaround I removed `ctrl+enter` keybinding from conflicting `editor.action.goToDeclaration`

**Comment by kasecato** [comment]
@hs-davydov Thank you for your report. I just fixed and published it on `v1.4.2`. Please check it.
