### ISSUE TITLE
ctrl+e or cmd+e : Recent files popup [bug]

### ISSUE THREAD

**Issue by ZobairQ** [kasecato/vscode-intellij-idea-keybindings#213]
Hello, 
The cmd +e or ctrl + e does not behave the same way it does inside intellij idea. 
# Problem Description
In intellij idea cmd + e or ctrl + e will show you a list of recently opened files within the given project. However in VSCODE the short will show you a list of every file opened with VSCODE. This means that you end up opening a whole new project. Especially if you are used to switch between to files with a quick cmd + e
 
# Solution
Instead this shortcut should be mapped to following command 

`@command:workbench.action.openPreviousEditorFromHistory`
This is more like the behaviour found in intellij idea

**Comment by kasecato** [comment]
@ZobairQ Hello, I just published `v1.4.1`. Please check it.

**Comment by gfx** [comment]
Thanks for developing this fantastic extension, @kasecato, and thanks to all the contributors for the efforts to keep this extension up to date. I heavily depend on this extension for my daily development!

BTW I think I have this problem with the latest vscode (`Version: 1.54.3`) and the latest extension (`1.4.2`). 

To be exact, `⌘+e` opens the "search files by name" selector, instead of quick open or open recent projects.

My environment is macOS and vscode remote into Ubuntu.

**Comment by kasecato** [comment]
Thank you so much for using this extension @gfx .

I just fixed and released it in [v.1.4.3](https://marketplace.visualstudio.com/items?itemName=k--kato.intellij-idea-keybindings). Please check it 🙇

CC: @ZobairQ

**Comment by gfx** [comment]
v1.4.3 looks perfect! 👏 👏 👏 

 Thank you for the quick fix!

**Comment by kasecato** [comment]
Thank you for your support. This is just my cat photos 🐾

![DSE09196](https://user-images.githubusercontent.com/10364603/111564187-a96d4e80-87dc-11eb-8c8b-ab6a4fcba1d9.JPG)

![DSE09201](https://user-images.githubusercontent.com/10364603/111564164-a2464080-87dc-11eb-99c3-1a49bc3c0bd3.JPG)

**Comment by ZobairQ** [comment]
Hello @ kasecato 
Thank you for your efforts, I just installed 1.4.3 and it seem to be reverting my changes and cmd + e show me a list of edited projects rather than showing me the history. However if you are in quickopen, let's you do cmd  + shift + P then you press cmd + e you get that history that we are requesting. if I am not mistaken then you should remove the `when: quickOpen` part and it should work

**Comment by kasperpeulen** [comment]
Removing when: quickOpen worked for me.

**Comment by kaichaosun** [comment]
Similar happens in the latest vscode, cmd+e is opening recent projects.
```
Version: 1.62.3 (Universal)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T07:59:13.865Z (6 days ago)
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.1.0
```

extension version: 1.5.0

**Comment by phil-bl** [comment]
still doesn't work (opens search) in extension version v1.5.4, VS Code 1.73.0
