### ISSUE TITLE
Granual control over which keymaps to enable?

### ISSUE THREAD

**Issue by bartenra** [kasecato/vscode-intellij-idea-keybindings#217]
Hi. I'd like to know if it's possible to only enable a few keymaps, while keeping the defaults for some others.

For example, VS Code's `ctrl+p` is ingrained in my memory.

**Comment by kasecato** [comment]
You can filter keybind by `intellij` and `Remove Keybinding` from Keyboard Shortcut settings.

![Screenshot 2024-02-23 150359](https://github.com/kasecato/vscode-intellij-idea-keybindings/assets/10364603/33016786-b09b-443e-87db-49dee9b51cd1)
