### ISSUE TITLE
wrong/missing commands for extract actions

### ISSUE THREAD

**Issue by Eskibear** [kasecato/vscode-intellij-idea-keybindings#230]
#### Extract Variable | ✅    

wrong refactoring kind (see [here](https://github.com/kasecato/vscode-intellij-idea-keybindings/blob/9cffce1b54ffa101a59bdfb9251ed49a418e50ab/package.json#L858)), should be `refactor.extract.variable`

####  Extract Field | N/A

refactoring available. should be `refactor.extract.field`

#### Extract Constant | N/A   
 
refactoring available. should be `refactor.extract.constant` (wrongly mapped to "variable" now)

#### Extract Parameter | N/A

There is a refactoring kind named as `refactor.introduce.parameter`, please check if it's matched.

### Reference
https://github.com/redhat-developer/vscode-java/blob/84d2985555251eaffd22dcb33f711a0e01f28b68/src/codeActionProvider.ts#L4-L18

**Comment by kasecato** [comment]
These refactoring features is fixed https://github.com/kasecato/vscode-intellij-idea-keybindings/pull/261
 
  - Extract Variable
  - Extract Field 
  - Extract Constant

These refactoring methods is added https://github.com/kasecato/vscode-intellij-idea-keybindings/pull/326
- Extract Parameter
- Change Signature

I was really surprised that `vscode-java` supported the Change Signature 👍
