### ISSUE TITLE
where to find keybinds file?

### ISSUE THREAD

**Issue by TheCodonist** [kasecato/vscode-intellij-idea-keybindings#236]

**Comment by FelipeFernandesLeandro** [comment]
> _No description provided._

https://github.com/kasecato/vscode-intellij-idea-keybindings/blob/master/src/package-with-comment.json

**Comment by Mahelita** [comment]
How come this link is not provided in the install instructions?
This feels very weird...
And why do we have to change the extension from json to xml to be able to import it?

**Comment by kasecato** [comment]
Please refer to the guide if you want to distribute changes to this extension
- https://github.com/kasecato/vscode-intellij-idea-keybindings?tab=readme-ov-file#contributing-to-the-code

If you want to delete the default key bindings of this extension in your own environment, please refer to the comments below
- https://github.com/kasecato/vscode-intellij-idea-keybindings/issues/217#issuecomment-1960780392

For the Importer, IntelliJ settings are exported as XML. This feature imports it (XML) into VS Code (JSON).
