### ISSUE TITLE
Ctrl keys in terminal should pass to shell 

### ISSUE THREAD

**Issue by jkottler** [kasecato/vscode-intellij-idea-keybindings#250]
OS: MacOS

When the terminal window has focus, keys should be sent to the terminal / shell instead of being captured by the keymaps.

For example: pressing `ctrl+r` in the terminal should activate my command line history search, not begin the `run` action.

This defect has caused me to disable the extension, which I was very pleased to find until I discovered this.

**Comment by hunterli** [comment]
{
    "key": "ctrl+r",
    "command": "workbench.action.terminal.sendSequence",
    "args": { "text": "\u0012" },
    "when": "terminalFocus"
  },

**Comment by kasecato** [comment]
Let me add a `ctrl+r` trigger when `editorFocus` only
