### ISSUE TITLE
editor.action.smartSelect.grow not working after VS Code February 2022 (version 1.65) update

### ISSUE THREAD

**Issue by semihsmg** [kasecato/vscode-intellij-idea-keybindings#253]
editor.action.smartSelect.grow command doesn't work with C#

**Comment by ellielle** [comment]
This may be an issue with VS Code itself, I'm not entirely sure yet. It _does_ work on some types of files for me on 1.65. So far I've found it still works with JavaScript, JSON, Markdown, and various flavors of CSS files still. They were the only file types I tried, so I can't speak to other languages, etc. What I can say is that it doesn't work for [Vue's Single File Components](https://v2.vuejs.org/v2/guide/single-file-components.html?redirect=true) at all now.

For now, I disabled auto updating in VS Code and downloaded 1.64.2, and everything works as it used to.

**Comment by semihsmg** [comment]
this issue solved with 1.65.2 update!
