### ISSUE TITLE
No code actions for 'source.overrideMethods' available

### ISSUE THREAD

**Issue by ikudosi** [kasecato/vscode-intellij-idea-keybindings#266]
Hello,

I am coming from Phpstorm and am trying to switch to VSCode. I even bought the premium version of the Intelephense extension and when I am trying to override method from an extended class with ctrl + o (as I would be in Phpstorm), I get a `No code actions for 'source.overrideMethods available'`. I am not sure if I need another extension to make this feature work or I am missing something? The same thing occurs when I try to implement interface methods with ctrl + i.

**Comment by kasecato** [comment]
@ikudosi I missed that the keybind for Java only. I fixed it only fire in Java.
