### ISSUE TITLE
Reformat document "ctrl + alt + l" is not working

### ISSUE THREAD

**Issue by londbell** [kasecato/vscode-intellij-idea-keybindings#276]
vscode version: 1.71.1(Universal)
vscode-intellij-idea-keybindings version:v1.5.3
WIth Vim version: "v1.23.2

Now it can only reformat one line after "ctrl + alt + l" even I haven't select some codes;
After change the keybindings for "formatSelection" from "ctrl+alt+l" to "ctrl+alt+y", then I can reformat the whole document after "ctrl + alt + l".

**Comment by huowenxuan** [comment]
Is just work on the current line
v1.5.2 ok

**Comment by kasecato** [comment]
@londbell @huowenxuan @long76 Thanks for your report, released on v1.5.4. Please check it.

**Comment by AAverin** [comment]
Does this issue also affect macs?
I am on 1.5.3 at the moment and `cmd+shift+l` formatting does something weird.

**Comment by kasecato** [comment]
yes, please use v1.5.4.

**Comment by long76** [comment]
> @londbell @huowenxuan @long76 Thanks for your report, released on v1.5.4. Please check it.

All ok, thanks!

**Comment by londbell** [comment]
> @londbell @huowenxuan @long76 Thanks for your report, released on v1.5.4. Please check it.

All ok, thanks!

**Comment by annisschen** [comment]
i use v1.5.4, but it still doesn't work.

**Comment by dudul** [comment]
Format selection doesn't work for me on v1.7.2.
vscode version: windows 1.91.0

**Comment by devsigner-xyz** [comment]
It also doesn't work for me. It was a few days ago but suddenly it stopped working.

extension version: 1.7.2
vscode: 1.94.2
