### ISSUE TITLE
“Ctrl+Alt+l”is not working, 

### ISSUE THREAD

**Issue by annisschen** [kasecato/vscode-intellij-idea-keybindings#291]
![image](https://user-images.githubusercontent.com/25473087/234508759-7b673e9e-8e96-45dc-b1b0-692968ebfaee.png)
i update my vscode to 1.77.3, but it pops this tip. I have already installed C++ extension.
![image](https://user-images.githubusercontent.com/25473087/234509295-ad0a0fb1-92e2-459d-bab6-fe0b3df92ed5.png)

**Comment by kasecato** [comment]
Formatter can be used after the file is saved
