### ISSUE TITLE
Add support for camel humps

### ISSUE THREAD

**Issue by a-stewart** [kasecato/vscode-intellij-idea-keybindings#300]
In IntelliJ, you can enable "CamelHumps" mode making it so various text editing operations have units by CamelHumps.

![image](https://github.com/kasecato/vscode-intellij-idea-keybindings/assets/150152/fd5656df-6333-4cf7-9684-3fc0b6e1f505)

For example, pressing "CTRL+DEL" when your cursor is at the end of "ActionResourcePath" would change it into "ActionResource" and if you did it again then "Action".

For example, pressing "CTRL+Arrow key" when your cursor is at the end of "ActionResourcePath" would put your cursor between "Resource" and "Path"

---

VS Code added support for subword navigation in 1.25:  
https://code.visualstudio.com/updates/v1_25#_subword-support

I wonder if we could create a setting for the IntelliJ keybindings extension and when use the when clause in keybindings to perform different commands based on that?

**Comment by kasecato** [comment]
I released it on v1.5.10 now. Please check it

**Comment by mammuth** [comment]
I just used the plugin (v1.5.12) and for me, the camel hump settings seem to get imported incorrectly. 

It generated:
```json
    {
        "command": "cursorWordRight",
        "key": "alt+[ArrowRight]",
        "when": "textInputFocus"
    },
    {
        "command": "cursorWordRightSelect",
        "key": "shift+alt+[ArrowRight]",
        "when": "textInputFocus"
    },
```
etc.


However, the command in vscode v1.85.1 seems to be `cursorWord**Part**Right` etc. After adding the `Part` to the commands, camel hump navigation works fine for me 😊     
Thanks for maintaining this extension!

**Comment by kasecato** [comment]
Let me add **Part**

**Comment by kasecato** [comment]
I'll update a README.md. We can't support the double-click option for now
