### ISSUE TITLE
[BUG] "Show Next Change" is mapped instead of "Go to Next Change"

### ISSUE THREAD

**Issue by rybak** [kasecato/vscode-intellij-idea-keybindings#310]
Thank you for developing and maintaining this VS Code extension. It allows me to not have to remember two sets of shortcuts, which is great.

##  Bug description

This bug applies to "Show Next Change" and to "Show Previous Change". IntelliJ IDEA has a pair of [shortcuts](https://www.jetbrains.com/help/idea/reference-keymap-win-default.html#global_vcs_actions):

> Next Change  <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>↓</kbd>
>
> Previous Change  <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>↑</kbd>

Both of these _immediately jump_ to the corresponding place in the file. They correspond to VS Code's commands `workbench.action.editor.nextChange` and `workbench.action.editor.previousChange`. Corresponding native shortcuts:

![image](https://github.com/kasecato/vscode-intellij-idea-keybindings/assets/624072/457a7285-8572-4f3f-9634-ea1dabb47d24)

But the extension IntelliJ IDEA Keybindings (v1.5.10) maps the IntelliJ IDEA's shortcuts to VS Code's "Show Next Change" (`editor.action.dirtydiff.next`) and "Show Previous Change" (`editor.action.dirtydiff.previous`) instead.

## Expected shortcuts

![image](https://github.com/kasecato/vscode-intellij-idea-keybindings/assets/624072/f31a2d79-9e81-4121-ae2a-6add9adbad59)

(screenshot was made by configuring the shortcuts manually by replacing both System and the extension's shortcuts)

## Actual shortcuts
![image](https://github.com/kasecato/vscode-intellij-idea-keybindings/assets/624072/bcca2682-19c0-492e-859a-8048555c35dc)

As far as I can tell, there is no way to jump/navigate to changed place in the code, once it is shown/peeked by these shortcuts. For example, when IntelliJ"s shortcut <kbd>ctrl</kbd>+<kbd>B</kbd> (`editor.action.goToDeclaration`) is used in VS Code, then the peeked locations can be navigated with VS Code's <kbd>F12</kbd> and with also with arrow keys.

**Comment by kasecato** [comment]
@rybak Thank you so much your details, I just released v1.5.11, check it please

**Comment by rybak** [comment]
Works for me in 1.5.11 without user overrides. Thank you!

![image](https://github.com/kasecato/vscode-intellij-idea-keybindings/assets/624072/0ce18ab8-212c-4718-bb24-06eb7c280ca1)
