### ISSUE TITLE
Ctrl/cmd+m goes to matching brace/paren

### ISSUE THREAD

**Issue by danielpaz6** [kasecato/vscode-intellij-idea-keybindings#316]
Hi, in mac
when pressing on CTRL+M when the cursor is at a brace/paren, it goes to the matching one.
I'd love to see this keymap being added to this plugin as well.

**Comment by kasecato** [comment]
This was released on v1.6.0
https://github.com/kasecato/vscode-intellij-idea-keybindings/issues/224
