### ISSUE TITLE
Add cmd+p to the keymap list (that will show last opened files)

### ISSUE THREAD

**Issue by danielpaz6** [kasecato/vscode-intellij-idea-keybindings#318]
In Jetbrains, when pressing CMD+E it lists the last recently opened files which is equal in my opnion to CMD+P in VSC, so it would be good to add this shortcut to the keybinding.

**Comment by kasecato** [comment]
This was fixed on v1.6.0
https://github.com/kasecato/vscode-intellij-idea-keybindings/pull/327
