### ISSUE TITLE
`jumpToNextSnippetPlaceholder` on `Enter` unexpected behaviour

### ISSUE THREAD

**Issue by vladkovac** [kasecato/vscode-intellij-idea-keybindings#343]
This keybinding recently started to interfere with basic editor behavior.

Command: `jumpToNextSnippetPlaceholder`
Keybinding: `Enter`
When: `editorTextFocus && hasNextTabstop && inSnippetMode`
Source: `IntelliJ IDEA Keybindings`

This gets triggered when accepting suggestion/autocomplete in some cases - instead of accepting selected suggestion cursor jumps outside of brackets.
Caught it in `JSX/TSX` syntax when working with attributes/props.

Removing this keybinding fixed the issue.

Steps to reproduce:

1. create an HTML `div` element in `js/ts/jsx/tsx` file
2. add `style` attribute. When editor suggests `style` - select it
```typescript
<div style={~cursor is here after accepting suggestion~} />
```
3. press `Enter`

Expected result:
```typescript
<div style={
     ~cursor is here~
} />
```

Actual result (cursor jumped outside of brackets):
```typescript
<div style={}~cursor is here~ />
```

This issue is not `JSX`-specific, happened in regular `JS/TS` as well. Seems to be related to `When` keybinding instructions and should be reproducible in other languages.

**Comment by lgou2w** [comment]
I'm having the same problem with the Rust language.

Pressing <kbd>Enter</kbd> when suggestion/autocomplete is in focus causes completion to fail!

![focus](https://github.com/kasecato/vscode-intellij-idea-keybindings/assets/13819168/cdc3c26e-b19d-4f64-9158-935902167634)

![failed](https://github.com/kasecato/vscode-intellij-idea-keybindings/assets/13819168/1ce61a9a-3208-45f3-bf76-3406d14fc392)

**Comment by baveku** [comment]
remove keybinding jumpToNextSnippetPlaceholder and it's worked.
I have been trying for 2 weeks to find the problem; :| I'm a snoop. right?

**Comment by kasecato** [comment]
Related with https://github.com/kasecato/vscode-intellij-idea-keybindings/issues/239 since v1.6.1

**Comment by kasecato** [comment]
Thanks for your detailed reporting, I just fixed and released it. Please check it
