### ISSUE TITLE
Missing multiple cursors shortcut

### ISSUE THREAD

**Issue by dawidk92** [kasecato/vscode-intellij-idea-keybindings#347]
### IntelliJ IDEA shortcut

Press <kbd>⌥ Opt</kbd> twice, and then without releasing it, press up or down arrow keys.

[JetBrains documentation](https://www.jetbrains.com/help/idea/multicursor.html#add-carets-above-or-below-the-current-caret)

### VSCode shortcut

By default it works by pressing <kbd>⌥ Opt</kbd> + <kbd>⌘ Cmd</kbd> + <kbd>↑</kbd>/<kbd>↓</kbd>

**Comment by kasecato** [comment]
Not supported on the VS Code side by default. Need an implementation to keep track of the `cmd`/`ctrl` state.

See https://github.com/kasecato/vscode-intellij-idea-keybindings/issues/173#issuecomment-1950995041

- duplicated with #173
- related with #121
