### ISSUE TITLE
Question on hotkey Shift-Esc

### ISSUE THREAD

**Issue by mondwan** [kasecato/vscode-intellij-idea-keybindings#354]
In #349, it fixed the hotkey shift+escape to Hide Active Tool Window. So, it can hide the terminal as expected. But, how can I "show" the terminal again?

Before the fix, I can "Shift+Escape" to hide the terminal, and pressing the same hotkey for getting the terminal back. After updating this plugin to latest version, however, I cannot do so.

Currently, I rolled back the key binding version due to this reason. Just wondering is there any way for configuring this plugin / vscode so that it can "show" the terminal again by pressing the same hotkey?

**Comment by kasecato** [comment]
This change emulates IntelliJ's shortcuts
We need to use `alt+f12` instead of `shift+esc` for the toggle terminal
https://github.com/kasecato/vscode-intellij-idea-keybindings/issues/103

**Comment by Skaldebane** [comment]
@kasecato While it's more consistent with IntelliJ, it's less convenient. Now every time I use the new keybinding, I get a new terminal, which sucks.

Since the previous `shift + esc` keybinding is now free, is it possible to keep the old default behavior (New or last used terminal) under that keybinding?

**Comment by mondwan** [comment]
@kasecato Thanks for the confirmations. But I agree with @Skaldebane point of view.

Any suggestion on how can we customise the configuration so that we can have the original behaviour if we want to?

Thanks for your time

**Comment by kasecato** [comment]
@Skaldebane @mondwan 
We can add the below keybinding to the `keybindings.json`
See https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization

```json
[
    {
        "key": "shift+escape",
        "mac": "shift+escape",
        "command": "workbench.action.terminal.toggleTerminal",
        "intellij": "Hide active or last active window (Terminal)"
    }
]
```

**Comment by Skaldebane** [comment]
@kasecato Thanks a lot! That works!

**Comment by wenduof** [comment]
Solved. Thans!
