### ISSUE TITLE
Fold & Collapse

### ISSUE THREAD

**Issue by anatooly** [kasecato/vscode-intellij-idea-keybindings#55]
VSCode
Fold (Ctrl+Shift+[) folds the innermost uncollapsed region at the cursor
Unfold (Ctrl+Shift+]) unfolds the collapsed region at the cursor
Fold All (Ctrl+K Ctrl+0) folds all region in the editor
Unfold All (Ctrl+K Ctrl+J) unfolds all regions in the editor

PhpStorm
Ctrl + Period (Ctrl + .) -> Toggle fold/unfold

**Comment by k--kato** [comment]
It is impossible to implement toggle fold/unfold.

**Comment by kasecato** [comment]
released this on v1.5.13
