### ISSUE TITLE
How to put one " ; " at the end of line

### ISSUE THREAD

**Issue by xliez** [kasecato/vscode-intellij-idea-keybindings#65]
While in jetbrains, 'ctrl+shift+enter' will end this line with a semicolon, I think it awesome and useful.

**Comment by stfnio** [comment]
It'd be awesome

**Comment by afloarea** [comment]
Would it be possible for JS files in particular, when using the `ctrl+shift+enter` shortcut, to append a semicolon based on the `Javascipt>Format Semicolons` setting of vscode?

Right now, to obtain the desired effect you have to do `ctrl+shift+enter` and then `ctrl+alt+l` to format (which actually formats the entire file).

Regardless of the outcome of this github issue, thank you for this great vs-code extension 🙏
