### ISSUE TITLE
Error Report Always Pop Up

### ISSUE THREAD

**Issue by rezashamdani** [kasecato/vscode-intellij-idea-keybindings#79]
Hi, first i want to say thank you for the great extension.

Some times i get error while typing some code,
<img width="1245" alt="screen shot 2017-06-19 at 11 02 34 am" src="https://user-images.githubusercontent.com/3622787/27269200-0901a3bc-54df-11e7-960e-2b90b7bb2e78.png">

Is there any setting to suppress it or how to solve it?

**Comment by kasecato** [comment]
Closed due to current cannot be reproduced
