### ISSUE TITLE
Duplicate selection (cmd + d)

### ISSUE THREAD

**Issue by xtravanta** [kasecato/vscode-intellij-idea-keybindings#80]
When a selection is made pressing **cmd + d** will duplicate complete line down not only the selection.

**Comment by gregbacchus** [comment]
here is a plugin that implements duplicate correctly, you can add it with your own keybinding

https://marketplace.visualstudio.com/items?itemName=rivenvirus.duplicatetext
https://github.com/rivenvirus/duplicateText/

**Comment by k--kato** [comment]
Thanks.
Resolved #88 , Released v0.2.14

**Comment by kasecato** [comment]
already supported cmd+d
