### ISSUE TITLE
Keybindings are not getting applied.

### ISSUE THREAD

**Issue by ninjaboy** [kasecato/vscode-intellij-idea-keybindings#84]
In VSCode version Version 1.15.0 (1.15.0) when I install IntelliJ keybindings extension as per installation instructions and after I restart VSCode new keyboard shortcuts are not getting applied and default ones stay instead.

Please let me know which information needs to be provided in order to help diagnose the issue

**Comment by pcegarra** [comment]
+1

**Comment by jokermonn** [comment]
+1

**Comment by k--kato** [comment]
@ninjaboy @pcegarra @jokermonn I released v0.2.14. Can you check if this problem is reproduced?

**Comment by dguay** [comment]
What's the ETA on this? I installed 0.2.15 from marketplace and some shortcuts aren't working (cmd+o, cmd+e, cmd+p just to name some...)

**Comment by kasecato** [comment]
@ninjaboy @pcegarra @jokermonn @dguay  This plugin can not be used after installing `Debugger for Java`.
```bash
ERROR Extension `vscjava.vscode-java-debug` failed to activate. Reason: unknown dependency `redhat.java`.
```

**Comment by dguay** [comment]
@kasecato I don't have `Debugger for Java` installed.

**Comment by kasecato** [comment]
@dguay Could you list installed extensions?

**Comment by dguay** [comment]
@kasecato 

- Dracula Official 2.8.0
- Ember JS (ES6) and Handlebars code snippets 2.2.0
- IntelliJ IDEA Keybindings 0.2.18

**Comment by kasecato** [comment]
@dguay Thanks. I could not reproduce it. 
- VS Code 1.19.3
- Dracula Official 2.8.0
- Ember JS (ES6) and Handlebars code snippets 2.2.0
- IntelliJ IDEA Keybindings 0.2.19
Please delete extension `~/.vscode/extensions/k--kato.intellij-idea-keybindings-0.2.xx/`.

**Comment by dguay** [comment]
@kasecato I deleted and reinstalled the extension. CMD+E just open recent projects and CMD+O open dialog for searching symbol (with the #)

**Comment by kasecato** [comment]
Closed due to can't reproduced in the current version
