### ISSUE TITLE
Option to use MacOX keymap in Windows/Linux

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [kasecato/vscode-intellij-idea-keybindings#86]
As related to #67 , to keep the consistency between cross platforms, I want use MacOX Keymap in Windows/Linux. I think this should be switchable

**Comment by marcondag** [comment]
And updates on this feature? It's something I'd really love given I use macOS at work and Windows/Linux at home.

**Comment by endlesscpp** [comment]
> And updates on this feature? It's something I'd really love given I use macOS at work and Windows/Linux at home.
> 
> In thinking about this however, there are probably some big problems re: macOS having both Control and Command, whereas Windows really only has Control available. Not sure what exactly would make sense as far as remapping those things go.

I'm looking forward to this feature too. On Linux we can map other key to COMMAND, this is NOT a problem. (Belows article is very useful for key mapping on Ubuntu)
https://askubuntu.com/questions/29731/rebind-alt-key-to-win-using-setxkbmap

**Comment by kasecato** [comment]
@ZhengshuaiPENG @saramarcondes @endlesscpp I released a importer of IntelliJ IDEA keymaps.
I hope you can macOS keymaps as Windows using this importer. Please check it.
https://marketplace.visualstudio.com/items?itemName=k--kato.intellij-idea-keybindings#intellij-importer-experimental-macos-only

**Comment by kasecato** [comment]
closed due to duplicate with #67
