### ISSUE TITLE
It does't work after update to vscode 1.17.1

### ISSUE THREAD

**Issue by 0kai** [kasecato/vscode-intellij-idea-keybindings#92]
all key shortcut been reset after I update the vscode to 2017 version.

reinstall also not work

**Comment by jevta78** [comment]
Also have the same problem

**Comment by kasecato** [comment]
@0kai @jevta78 This plugin can not be used after installing `Debugger for Java`.
```bash
ERROR Extension `vscjava.vscode-java-debug` failed to activate. Reason: unknown dependency `redhat.java`.
```

**Comment by AtticusLv** [comment]
same problem +1

**Comment by kasecato** [comment]
Can't reproduce for now
