### ISSUE TITLE
Cmd + y to remove a line does not work

### ISSUE THREAD

**Issue by justanirudh** [kasecato/vscode-intellij-idea-keybindings#94]
In IntelliJ, to remove a line, you can do Cmd + y. That does not seem to work in vscode after installation of the plugin

**Comment by spik3s** [comment]
I've checked with PHPStorm and WebStorm and removing a line is done with `CMD+Backspace` not  `CMD + Y`, and that functionality works.

**Comment by apahne** [comment]
IntelliJ (Ultimate) user here with MacOS key bindings. CMD-Y deletes a line in the default settings and I also miss it.

**Comment by nesl247** [comment]
Is this on the older macOS keybindings that I believe are there for BC reasons?

**Comment by gagan0723** [comment]
On IntelliJ IDEA, on Mac `cmd + y` does nothing. Instead `cmd + delete` deletes a line at the cursor.

**Comment by gdagitrep** [comment]
@nesl247 @totsteps , I don't think that's the case. My keyboard layout is US and both Intellij Classic and Ultimate use CMD+Y for delete. Even got a snapshot: 
<img width="897" alt="Screen Shot 2020-01-20 at 5 19 56 PM" src="https://user-images.githubusercontent.com/4613234/72767629-795ef700-3ba9-11ea-9c06-13bf5c8616a5.png">

**Comment by nesl247** [comment]
@gdagitrep those are the Classic keybindings. Those are not the default key bindings on any platform to my knowledge.

**Comment by kasecato** [comment]
closed due to duplicate with #67
