### ISSUE TITLE
Cmd+E opens Recent Projects popup instead of current project's Recent Files

### ISSUE THREAD

**Issue by spik3s** [kasecato/vscode-intellij-idea-keybindings#97]
In IntelliJ IDEA editors `CMD+E` opens a list of recently active files/tabs of currently opened project. Repeated keypresses navigate to next file on the list.

Meanwhile, currently in VSCode after applying the IntelliJ IDEA keybindings` CMD+E` opens a popup list of recent projects.

The closest behaviour to IntelliJ's `CMD+E` is 'Open Next Recently Used Editor In Group' command (`CTRL+TAB` by default).

**Comment by spik3s** [comment]
I suppose a further discussion should take place. After working with 'Open Next Recently Used Editor In Group' action under `CMD+E` for last two days, now I'm considering if maybe switching to 'Quick Open' and `workbench.action.quickOpenNavigateNextInFilePicker` command would be a better alternative? (under `CMD+P` by default ). Drawback is that `CMD+P` requires a double keypress to navigate to the next (previously opened) file.

**Comment by kasecato** [comment]
@spik3s Thanks for your report and PR! I did released today. Please check it.

**Comment by antoniopaisfernandes** [comment]
Had to downgrade to 0.2.16:

![image](https://user-images.githubusercontent.com/6171197/34361556-0c8158b0-ea63-11e7-8069-a538d5c0315a.png)

![image](https://user-images.githubusercontent.com/6171197/34361568-210b8dc8-ea63-11e7-9fd7-3c487006f8af.png)

**Comment by kasecato** [comment]
@antoniopaisfernandes thanks. I will fix it.

**Comment by kasecato** [comment]
I think @spik3s suggestions is right, it is close to the operation of Intellij. I don't change this.

**Comment by DaanDeMeyer** [comment]
Are you sure ctrl+e is operating as it should right now? ctrl+e opens a list of recent files in Intellij. With this extension it opens a list of recent projects. This seems very different compared to what Intellij does.

**Comment by mostafaznv** [comment]
> Are you sure ctrl+e is operating as it should right now? ctrl+e opens a list of recent files in Intellij. With this extension it opens a list of recent projects. This seems very different compared to what Intellij does.

Agree
Is there any workaround?

**Comment by bcho** [comment]
I remapped the key to command: "Go to File..." (which is `cmd+p` before)
